In [2]:
import numpy as np

def print_matrix(matrix):
    for row in matrix:
        print(' '.join(f'{elem:10.4f}' for elem in row))
    print()

n = int(input("n = "))

A = np.random.randint(0, 100, size=(n, n)).astype(np.float32)
b = np.random.randint(0, 100, size=n).astype(np.float32)

original_A = A.copy()
original_b = b.copy()

augmented = np.hstack((A, b.reshape(-1, 1)))

print("\nGenerated matrix A and vector b:")
print("A =")
print(A)
print("b =", [f"{x:.4f}" for x in b])
print("\nInitial augmented matrix:")
print(augmented)

# Gaussian elimination with step-by-step matrix output
for k in range(n - 1):
    for i in range(k + 1, n):
        pivot = augmented[k, k]
        if pivot == 0:
            print(f"Zero pivot encountered at row {k}. Cannot proceed.")
            exit()
        multiplier = augmented[i, k] / pivot
        for j in range(k, n + 1):
            augmented[i, j] -= multiplier * augmented[k, j]

        # print(f"After eliminating row {i} using pivot row {k}:")
        # print_matrix(augmented)


print_matrix(augmented)


x = np.zeros(n, dtype=np.float32)
for i in range(n - 1, -1, -1):
    sum_val = 0.0
    for j in range(i + 1, n):
        sum_val += augmented[i, j] * x[j]
    x[i] = (augmented[i, n] - sum_val) / augmented[i, i]

print("x: ")
for xi in x:
    print(f"{xi:.4f}")

# Calculate residual R = Ax - b
residual = []
for i in range(n):
    ax_i = 0.0
    for j in range(n):
        ax_i += original_A[i, j] * x[j]
    residual.append(ax_i - original_b[i])

inf_norm = max(abs(val) for val in residual)
print(f"\nResidual (infinity norm): {inf_norm:.7f}")

n = 5

Generated matrix A and vector b:
A =
[[39. 67. 80. 65. 93.]
 [42. 22. 95. 51. 16.]
 [47. 94. 99. 29.  1.]
 [73. 55. 69. 30. 36.]
 [ 3. 56.  3. 76. 72.]]
b = ['63.0000', '73.0000', '73.0000', '54.0000', '14.0000']

Initial augmented matrix:
[[39. 67. 80. 65. 93. 63.]
 [42. 22. 95. 51. 16. 73.]
 [47. 94. 99. 29.  1. 73.]
 [73. 55. 69. 30. 36. 54.]
 [ 3. 56.  3. 76. 72. 14.]]
After eliminating row 1 using pivot row 0:
   39.0000    67.0000    80.0000    65.0000    93.0000    63.0000
   -0.0000   -50.1538     8.8461   -19.0000   -84.1539     5.1538
   47.0000    94.0000    99.0000    29.0000     1.0000    73.0000
   73.0000    55.0000    69.0000    30.0000    36.0000    54.0000
    3.0000    56.0000     3.0000    76.0000    72.0000    14.0000

After eliminating row 2 using pivot row 0:
   39.0000    67.0000    80.0000    65.0000    93.0000    63.0000
   -0.0000   -50.1538     8.8461   -19.0000   -84.1539     5.1538
    0.0000    13.2564     2.5897   -49.3333  -111.0769    -2.9231
  